name: Moovie
author:
    - Colin Aarts
    - Nathan Bishop
category: Media
tags: [
    video,
    html5,
    media,
    mootools,
    player,
    captions,
    subtitles,
    playlist
]
#docs: https://github.com/nbish11/Moovie/wiki
#demo: https://github.io/nbish11/Moovie
#current: 1.0.0